export default {
  progress: '.progress',
  placeAddBtn: '.place__add-btn',
  placeCancelBtn: '.place__cancel-btn',
  placeCreateBtn: '.place__create-btn',
  placeDeleteBtn: '.place__delete-btn',
  placeAddPhotoBtn: '.place__add-photo-btn',
  placeReviews: '.place__reviews',
  placeReviewBtn: '.place__review-btn',
  placeReviewsBtn: '.place__reviews-btn',
  placeReviewForm: '.place__review-form',
  placeReviewFormSubmitBtn: '.place__review-form .btn',
  places: '.place__results',
  place: '.place__item',
};
